# enable labeler on issues, prs, or both.
enable:
  issues: false
  prs: true

# 레이블 규칙
labels:
  '✨ Feature':
    include:
      - '\bfeat\b'
  '🐞BUG':
    include:
      - '\bfix\b'
  '🔨 Refactor':
    include:
      - '\brefactor\b'
  '📬 API':
    include:
      - '\bapi\b'
  '📃 Docs':
    include:
      - '\bdocs\b'
  '🌏 Deploy':
    include:
      - '\bdeploy\b'
  '🎨 Style':
    include:
      - '\bstyle\b'
  '💻 CrossBrowsing':
    include:
      - '\bcrossbrowsing\b'
  '✅ Test':
    include:
      - '\btest\b'
  '⚙ Setting':
    include:
      - '\bsetting\b'
