// (auto-generated) Do not edit manually.
// Run `pnpm build:icons` to regenerate.

export {default as IcSvgComponent1} from './ic_component1';
export {default as IcSvgArrowLeft} from './ic_arrow_left';
export {default as IcSvgCart} from './ic_cart';
export {default as IcSvgCheckLg} from './ic_check_lg';
export {default as IcSvgCheckSm} from './ic_check_sm';
export {default as IcSvgChevronDownSm} from './ic_chevron_down_sm';
export {default as IcSvgChevronRight} from './ic_chevron_right';
export {default as IcSvgChevronRightSm} from './ic_chevron_right_sm';
export {default as IcSvgChevronUp} from './ic_chevron_up';
export {default as IcSvgClose} from './ic_close';
export {default as IcSvgCloseSm} from './ic_close_sm';
export {default as IcSvgDelivery} from './ic_delivery';
export {default as IcSvgMap} from './ic_map';
export {default as IcSvgMenu} from './ic_menu';
export {default as IcSvgMinus} from './ic_minus';
export {default as IcSvgNotice} from './ic_notice';
export {default as IcSvgPlus} from './ic_plus';
export {default as IcSvgQuestion} from './ic_question';
export {default as IcSvgSearch} from './ic_search';
export {default as IcSvgStar} from './ic_star';
